### ISSUE TITLE
Color of 'Zurück zur Händlersuche' link is to light 

### ISSUE THREAD

**Issue by aschieweck** [lokalkauf/lokalkauf-frontend#108]
**Describe the bug**
The 'Zurück zur Händlersuche' link on a trader details page is light grey on a white background. This makes it impossible to read.

**To Reproduce**
1. Go to any trader details page'
2. Try to find the 'Zurück zur Händlersuche' link on the top or bottom of the page
3. See the problem

**Expected behavior**
The link should have a clear contrast.

**Screenshots**
![DeepinScreenshot_select-area_20200502155931](https://user-images.githubusercontent.com/13769553/80867802-eea09480-8c8d-11ea-8dea-615ecbfbd5ce.png)

**Device and OS:**
 - Computer wiht Manjaro Linux
 - Chrome 81

**Comment by christianaschoff** [comment]
Good point, but it is accurate regarding the new design.
Maybe we should challenge that :)

**Comment by christianaschoff** [comment]
done
