### ISSUE TITLE
Radius of trader search is only restricted in the UI

### ISSUE THREAD

**Issue by aschieweck** [lokalkauf/lokalkauf-frontend#109]
**Describe the bug**
The radius of the trader search is only restricted in the UI. One can easily change the URL parameter to query the whole database. The slider even shows the too large values.

**To Reproduce**
1. Start a valid search for any city. 
2. Change the last number in the URL, i.e. after the last '/', to something ridiculously large, e.g. 999999
3. Wait for the page to load all entries

**Expected behavior**
The radius should always be restricted to some reasonable distance. 
Might be fixed with the map view?

**Screenshots**
![DeepinScreenshot_select-area_20200502160142](https://user-images.githubusercontent.com/13769553/80867848-53f48580-8c8e-11ea-8daf-4c8b11ec9906.png)

**Device and OS:**
 - Computer with Manjaro Linux
 - Chrome 81

**Comment by lukaesch** [comment]
URL query validation in place and works.
