### ISSUE TITLE
Serch radius set to 0 and all shops shown

### ISSUE THREAD

**Issue by buecheko** [lokalkauf/lokalkauf-frontend#111]
**Describe the bug**
The app detects my position and sets it to "PLZ City (mein Standort)". After hitting "Geschäft suchen" the radius is set to 0 and all shops are listed.

**To Reproduce**
1. Enable GPS
2. Go to the start page
3. Wait until the correct location is shown
4. Press "Geschäft suchen"

**Expected behavior**
The default radius should not be set to 0. There is one Shop in my city in a 5km radius which should show up.

**Screenshots**
![wrong_default_radius](https://user-images.githubusercontent.com/50521948/80868298-f1a18200-8c99-11ea-969f-a4cf58cac7e9.png)

**Device and OS:**
 - Device: Moto g6, Android 9
 - Browser/Version Chrome v81.0.4044.117

**Comment by christianaschoff** [comment]
known bug - should be resolved by #110

**Comment by buecheko** [comment]
Confirmed :+1:

**Comment by lukaesch** [comment]
Bug resolved
