### ISSUE TITLE
social link icons are not shown

### ISSUE THREAD

**Issue by owlRike** [lokalkauf/lokalkauf-frontend#113]
Only Instagram icon is displayed when choosing region without trader (see screenshot)
![grafik](https://user-images.githubusercontent.com/64211488/80910772-1c3f1980-8d32-11ea-9bc6-8cf04523eae5.png)

in safari and chrome

**Comment by christianaschoff** [comment]
Yeah, noticed that as well. After refreshing the gage, all was fine again.
I guess, we should not relay on CDN stuff for that.
Insta is the only icon provided by us and not by a CDN if I remember right.

Pleased give it a shot by refreshing the browser

**Comment by owlRike** [comment]
yep, when refreshing, the icons appear.

**Comment by christianaschoff** [comment]
@patsimm can you have a look into that? 
Happened to me, too.  Appeared after caching merge I guess.
