### ISSUE TITLE
when pictures are deleted there is no default picture shown on trader list

### ISSUE THREAD

**Issue by owlRike** [lokalkauf/lokalkauf-frontend#115]
Even after refreshing the page, it's still shown like in the screenshot.
![grafik](https://user-images.githubusercontent.com/64211488/80911574-65459c80-8d37-11ea-9000-9b2faeb0713a.png)

**Comment by thecodemonkey** [comment]
The problem is probably the sync mechanism between traders and the locations.

**Comment by thecodemonkey** [comment]
done.
