### ISSUE TITLE
No Twitter, Facebook, WhatsApp Image

### ISSUE THREAD

**Issue by JnSnw** [lokalkauf/lokalkauf-frontend#120]
**Describe the bug**
If you search a location, where is no trader. The Images for the Social Media links are missing.
Only if you reload the page, the images will appear.

**To Reproduce**
1. Go to a location, where is no trader
2. See missing images of social media links

**Screenshots**
![image](https://user-images.githubusercontent.com/28543964/80917535-e57ff800-8d5f-11ea-9868-dd19e7b93e12.png)

**Comment by christianaschoff** [comment]
dublicate of https://github.com/lokalkauf/lokalkauf-frontend/issues/113
