### ISSUE TITLE
Whatsapplink in Firefox doesn't work

### ISSUE THREAD

**Issue by JnSnw** [lokalkauf/lokalkauf-frontend#121]
**Describe the bug**
If you click on the Whatsapplink in an area without a trader, no page appears in Firefox, or the page is not found because whatsapp:// is recognized as protocol.

**To Reproduce**
1. Go to location without a trader
2. Click on whatsapp social link
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/28543964/80917605-63dc9a00-8d60-11ea-9877-4a107fe91679.png)

**Device and OS:**
 - Firefox

**Comment by christianaschoff** [comment]
do you have the whatsapp desktop app running?

**Comment by owlRike** [comment]
doesn't work on Safari either.
But I don't have Whatsapp App on the MacBook. But it worked properly on Chrome.

**Comment by christianaschoff** [comment]
ah, interesting...
All browsers target the same url. Firefox and safari get redirected to a whatsapp:// url, while chrome stays on the message-page.
You can see that when using the browser back button in FF or Safari.

**Comment by christianaschoff** [comment]
https://medium.com/@jeanlivino/how-to-fix-whatsapp-api-in-desktop-browsers-fc661b513dc

**Comment by christianaschoff** [comment]
ah, we use the api-Endpoint. Should work on all mobile browsers.
It seems that we need to use the web-Endpoint for desktop.
Chrome seems to work fine with both. Safari und FF get brute force forwarded to another page.

https://webapps.stackexchange.com/questions/106145/whatsapp-link-with-phone-number-doesnt-open-whatsapps-web-app

My question: is that social link worth the effort?
If so: we need a browser detection stating what browser we are on and on what device.
I thing there are some capable npm-packages for that.
Then we need some forks in code to tamper the url.

Who ever implements that: please consider to hide the npm package behind some kind of service, please. Those libs tend to be tricky at the edge-cases, so we might have to try some.

**Comment by lukaesch** [comment]
Works on macOS/Firefox, macOS/Safari and macOS/Chrome
