### ISSUE TITLE
Wrong Address if you confirm to fast

### ISSUE THREAD

**Issue by JnSnw** [lokalkauf/lokalkauf-frontend#122]
**Describe the bug**
If the address is changed, and this is confirmed before it reaches the location in the map, the incorrect address is adopted.

**To Reproduce**
1. Go to 'Mein Händlerprofil'
2. Click on 'Allgemein' -> Mein Adressdaten bearbeiten
3. Change PLZ and Stadt
4. Klick Standort bestätigen
5. Immediately click on confirm
6. Save your change.
7. See in trader search that the trader will still shown in the old location, but the address is chaged.

**Screenshots**
![image](https://user-images.githubusercontent.com/28543964/80917721-33493000-8d61-11ea-90e1-255cf66ce4bd.png)

**Comment by christianaschoff** [comment]
Ah, you mean while the animation is shown and the map flies to the desired new position? Interesting. Good point. 
@thecodemonkey: is there an event to determine if the animation is done? 
@JnSnw: might disabling the button during the animation be a valid solution to this to you?

**Comment by lukaesch** [comment]
Confirm button shows up after effect only.
