### ISSUE TITLE
Traders from Nürnberg (around 270km away) are shown in Wiesbaden

### ISSUE THREAD

**Issue by owlRike** [lokalkauf/lokalkauf-frontend#123]
see screenshot
![grafik](https://user-images.githubusercontent.com/64211488/80921927-db6af300-8d79-11ea-98e5-4b4c2e12c3f9.png)

**Comment by thecodemonkey** [comment]
i think it is the same problem as with Issue #122

**Comment by christianaschoff** [comment]
due to test data that was tampered with this behaviour was intended in that case :)
