### ISSUE TITLE
pictures don't upload on safari

### ISSUE THREAD

**Issue by owlRike** [lokalkauf/lokalkauf-frontend#127]
I cannot upload any picture on safari. The same pictures worked on Chrome.

Safari version: 12.0

**Comment by buecheko** [comment]
Unfortunately this is a known bug. Safari 12 is an outdated version and is not longer supported by apple. For security reasons and for better compatibility Safari should be updated to the current version (13).
Issue #73 will be our workaround.

**Comment by owlRike** [comment]
So, we cannot adjust this, but give clients the info they need to update their browser if we get the info, that the upload doesn’t work?

**Comment by thecodemonkey** [comment]
There is already a ticket #73 for it. But there are also several technical ways, we have to talk about them first.

**Comment by christianaschoff** [comment]
@owlRike - exactly
