### ISSUE TITLE
New Page - Supporters

### ISSUE THREAD

**Issue by MaximilianSei** [lokalkauf/lokalkauf-frontend#161]
A new page like "presse über uns" with supporters:

Esther Constantin - Design / UX Design - fuenfwerkenm design AG
Skirmante XYZ - Design / UX Design - fuenfwerken design AG
Christian Welkenbach - Rechtsanwalt / Partner - TCI Rechtsanwälte Mainz
Elena - Presse 
Oliver - Film

**Comment by christianaschoff** [comment]
isnt it more suitable if we add another section on the page "about us"?

**Comment by MaximilianSei** [comment]
Yes lets start like this!

**Comment by christianaschoff** [comment]
Skirmante XYZ - thats the name for real?

**Comment by MaximilianSei** [comment]
Vielen Dank für eure Unterstützung des lokalen Einzelhandel und Gastronomie (Herz)

Esther Constantin - Design / UX Design - Fuenfwerken Design AG
Skirmante Rudaviciute - Design / UX Design - Fuenfwerken Design AG
Christian Welkenbach - Rechtsanwalt / Partner - TCI Rechtsanwälte Mainz
Oliver Geibel - Film Storyboad - Northwind Visuals Film
Elena Funk - Pressetexte

**Comment by owlRike** [comment]
Please change text to:
Vielen Dank für Eure Unterstützung des lokalen Einzelhandels und der Gastronomie (Herz)

Esther Constantin – Design / UX Design – Fuenfwerken Design AG
Skirmante Rudaviciute – Design / UX Design – Fuenfwerken Design AG

Christian Welkenbach – Rechtsanwalt / Partner – TCI Rechtsanwälte Mainz

Oliver Geibel – Film Storyboad – Northwind Visuals Film

Elena Funk – Pressetexte
