### ISSUE TITLE
Products: Thumbnail-Preview on trader-page is not loaded at once

### ISSUE THREAD

**Issue by christianaschoff** [lokalkauf/lokalkauf-frontend#183]
Thumbnail is only shown if the page is reloaded. Otherwise the "heart" is shown, even if the thumbnail is generated.

**Comment by Dipanjana1990** [comment]
@christianaschoff: How can I test this exactly? For me the trader page opened everytime  immediately

**Comment by christianaschoff** [comment]
@Dipanjana1990 it is not about trader page, but about products in the product-configuration-page where you can create new products and upload images. After images are uploaded, the thumbnail of that product should be shown immediately. 
That was not the case before that bugfix.

You can create a new product for a trader and check, if there is thumbnail shown afterwards when returning to the product-overview on the same page. If so, everything is fine.

**Comment by Dipanjana1990** [comment]
It is slow but thumbnail is displayed
![image](https://user-images.githubusercontent.com/68644410/117707513-f4995180-b1ce-11eb-968a-850d62b0b45e.png)
