### ISSUE TITLE
Image-Upload: There is no "type"-Filter for the file that can be selected.

### ISSUE THREAD

**Issue by christianaschoff** [lokalkauf/lokalkauf-frontend#184]
If file-format is not supported, there is no message shown at all. There is just nothing happening after upload of an unsupported file.
Some userfeedback in advance or after the file is processed would be nice

**Comment by darkblackside** [comment]
I've got a message on the products upload, as well as the images for the trader. Am I missing some point? Do you have an example for the error?

**Comment by christianaschoff** [comment]
my bad - last time I checked there was no toast message when the file format was not supported.
Closing the issue

**Comment by Dipanjana1990** [comment]
![image](https://user-images.githubusercontent.com/68644410/117705541-763bb000-b1cc-11eb-8719-80fc535f63de.png)
