### ISSUE TITLE
Changes Textes on Starting Page!

### ISSUE THREAD

**Issue by christianaschoff** [lokalkauf/lokalkauf-frontend#199]

**Comment by owlRike** [comment]
Please write "Deine" with capital D
![grafik](https://user-images.githubusercontent.com/64211488/89311530-6956c280-d676-11ea-8358-5e7ebe114360.png)

**Comment by owlRike** [comment]
Bitte noch ein Leerzeichen einfügen: 
![grafik](https://user-images.githubusercontent.com/64211488/89312619-c30bbc80-d677-11ea-999f-e94356cc7a49.png)
