### ISSUE TITLE
Feedback-Form requires a valid e-mail-adress, but the given text implies, that an e-mail is optional.

### ISSUE THREAD

**Issue by christianaschoff** [lokalkauf/lokalkauf-frontend#212]

**Comment by Dipanjana1990** [comment]
@christianaschoff : The same error message appears for an invalid Email or empty message field or if the AGB and Data privacy conditions are not accepted or any combination of the three errors. Is this the expected result.

![image](https://user-images.githubusercontent.com/68644410/112874695-88054000-90c3-11eb-9ea5-97fb9bea031c.png)

**Comment by christianaschoff** [comment]
#feelingBad - dont think so - @darkblackside might look into that...

**Comment by darkblackside** [comment]
I think that was the originally intended behaviour, but it is easy to change that. So you think the behaviour should be a different error message for each field?
@Dipanjana1990, @christianaschoff

**Comment by christianaschoff** [comment]
@darkblackside yes ist was, but makes more sense to display the correct message directly at each field, doesnt it?
