### ISSUE TITLE
Add share button on trader detail page

### ISSUE THREAD

**Issue by christianaschoff** [lokalkauf/lokalkauf-frontend#213]
Share specific Store directly on SoMe

**Comment by owlRike** [comment]
![grafik](https://user-images.githubusercontent.com/64211488/99905125-1a897300-2ccf-11eb-84a0-2089d497a669.png)
I receive this message, when trying to share a store on Facebook

**Comment by christianaschoff** [comment]
That is the same link, but another message that we use on the public share area.
Does this one still work?

**Comment by christianaschoff** [comment]
I get the same message from facebook on both ways that the message:
![Bildschirmfoto 2020-11-28 um 10 52 42](https://user-images.githubusercontent.com/13931688/100499196-dcc19a00-3167-11eb-95ac-d085d73effae.png)

@lukaesch maybe you can have a look into that?

**Comment by christianaschoff** [comment]
please check again - seems to work now again - was a facebook bug

**Comment by Dipanjana1990** [comment]
I was able to share without any error but instead of the trader page Lokalkauf .org was posted.

**Comment by christianaschoff** [comment]
hmmm - might need to have another look into it

**Comment by christianaschoff** [comment]
Just tried it on security-testing with my FB account and all meta data is displayed correctly.
![grafik](https://user-images.githubusercontent.com/13931688/116809836-8dc9c780-ab40-11eb-97de-312af1efdf2b.png)

**Comment by Dipanjana1990** [comment]
@christianaschoff When I am clicking the below icon

![image](https://user-images.githubusercontent.com/68644410/117716702-3380d480-b1da-11eb-9fdc-3cae142e3506.png)


then I am able to post about Lokalkauf but not exactly the store. Am I testing it incorrectly?
![image](https://user-images.githubusercontent.com/68644410/117716617-1b10ba00-b1da-11eb-9048-bb67a057a137.png)

**Comment by christianaschoff** [comment]
@Dipanjana1990 that is the general share on facebook link.
The other sharing functionality is "just" on security-testing and not on staging

![grafik](https://user-images.githubusercontent.com/13931688/118470638-26e30b80-b707-11eb-88d7-38a17bff53c7.png)

**Comment by Dipanjana1990** [comment]
tested and is Okay

![image](https://user-images.githubusercontent.com/68644410/118528950-3ed88080-b743-11eb-97f1-0d8f0ae8c9bd.png)
