### ISSUE TITLE
While choosing the category of the shop in "Händlerprofil"an error is appearing when choosing less than 1 or more than 2 categories but the Settings can still be saved  even though the save button  is greyed out.

### ISSUE THREAD

**Issue by Dipanjana1990** [lokalkauf/lokalkauf-frontend#218]
While choosing the category of the shop in "Händlerprofil"an error is appearing when choosing less than 1 or more than 2 categories but the website is letting me save it even though the save button  is greyed out. As a result sometimes the shop is appearing in all the category filters and sometimes only while applying the "Alle" filter. 
Observed both in Android and Mac
![New](https://user-images.githubusercontent.com/68644410/90432889-46db9500-e0cb-11ea-8c4a-01a91ba3d087.PNG)

**Comment by christianaschoff** [comment]
was that a newly created account and you observed that when filling out your profile initially? 
I tried that on an existing account and could not reproduce that.
Can you provide more infos please?

**Comment by Dipanjana1990** [comment]
Yes. It was a newly created Account. I had checked it 2 months ago, I will check it once again and let you know

**Comment by Dipanjana1990** [comment]
I tested it again with a newly created account while filling out the profile initially

![image](https://user-images.githubusercontent.com/68644410/98019133-af502d80-1e01-11eb-9fb1-223f002fa9e2.png)

**Comment by christianaschoff** [comment]
interesting case. I need to look into it.
What browser and what OS are you using?

**Comment by Dipanjana1990** [comment]
Browser- Microsoft Edge and OS- Windows 10 Enterprise

**Comment by christianaschoff** [comment]
what edge version are you using?

**Comment by christianaschoff** [comment]
had nothing todo with browser or os. Was a general bug in our implementation.
have a look at test-env, just deployed a new version

**Comment by Dipanjana1990** [comment]
The Defect still exits- tested for new and old Händlerprofil. Tested in Google Chrome and Edge.
![image](https://user-images.githubusercontent.com/68644410/109430699-f8586d00-7a02-11eb-92e1-2f70f99ef579.png)

**Comment by Dipanjana1990** [comment]
tested and is okay. I couldnot save the changes when I didnot choose any of teh category or when I cose more than two categories.
It can be saved when one or two categories are chosen

![image](https://user-images.githubusercontent.com/68644410/117702701-27404b80-b1c9-11eb-851b-ef21a2de0a8e.png)
![image](https://user-images.githubusercontent.com/68644410/117702813-4dfe8200-b1c9-11eb-9cd2-1b16e4a412d3.png)
![image](https://user-images.githubusercontent.com/68644410/117702922-6f5f6e00-b1c9-11eb-8ce2-5191ad0a5245.png)
