### ISSUE TITLE
New Supporters

### ISSUE THREAD

**Issue by MaximilianSei** [lokalkauf/lokalkauf-frontend#219]
Christian Welkenbach - Datenschutz (TCI Rechtsanwälte)
Dipanjana Chaudhuri - Testing 
Elena Funk - Presse 
Esther Constantin - Design / UX Design
Mahesh Iyer - Konzeption Storyboard Film (Brandscape GmbH)
Skirmante Rudaviciute - Design / UX Design (Fuenfwerken Design AG)
Stefan Scholz - Filmschnitt (Brandscape GmbH)

**Comment by christianaschoff** [comment]
we should revisit that ticket

**Comment by christianaschoff** [comment]
@MaximilianSei any news of yet?
Lukas 2 should not be mentioned.
Dipa for sure
Mahesh -> dont know the full name or function.

Please provide the information

**Comment by MaximilianSei** [comment]
See new updated comment. Please copy the whole text! :)

**Comment by MaximilianSei** [comment]
Looks great!
