### ISSUE TITLE
Update - Press Clippings

### ISSUE THREAD

**Issue by MaximilianSei** [lokalkauf/lokalkauf-frontend#220]
Impact Hub BerlinImpact Hub Berlin
#WirVsVirus: Solution Builder in the Spotlight - Impact Hub Berlin
We spoke with social innovators from three teams in the #WirVsVirus Solution Builder acceleration programme to learn about their COVID-19 innovations.
https://berlin.impacthub.net/wirvsvirus-solutionbuilder/

**Comment by christianaschoff** [comment]
where exactly should we place that? And we need a german text if it should place it on the front page

**Comment by christianaschoff** [comment]
@MaximilianSei any updates on that issue yet?

**Comment by MaximilianSei** [comment]
Please put in in the overview above the "welt". The welt and bitcome stays on the front page. As the article is in English we keep the English language.

Headline:
 #WirVsVirus – the world’s biggest online hackathon – the nine teams selected for its Solution Builder follow-up programme delivered their Demo Day pitches.

**Comment by MaximilianSei** [comment]
Logo

Headline:
#WirVsVirus – the world’s biggest online hackathon – the nine teams selected for its Solution Builder

Text:
We caught up with representatives from three of these fledgling organisations: lokalkauf; quarano; and RemedyMatch, to hear about their innovative solutions to COVID-19-related problems.

![Copy of RED-Berlin-DG_G-Suite](https://user-images.githubusercontent.com/64410346/108885924-aaa9c200-7608-11eb-9a98-5e6c3253cb46.png)

**Comment by MaximilianSei** [comment]
Thanks Christian! :)
