### ISSUE TITLE
Enable sellers to add a "Shop now" button

### ISSUE THREAD

**Issue by lukaesch** [lokalkauf/lokalkauf-frontend#238]
Acceptance criteria
- We have a 4rd tab in the seller settings where sellers can add a URL of a website where customers can buy their product and/or services

- If a seller added a URL, a "Shop now" button will be visible on their seller profile page

**Comment by Dipanjana1990** [comment]
Funstions as expected.

![image](https://user-images.githubusercontent.com/68644410/108635255-ce410100-747e-11eb-82f7-eb1defef644b.png)

![image](https://user-images.githubusercontent.com/68644410/108635237-b7021380-747e-11eb-9b33-91d914f1cd66.png)
