### ISSUE TITLE
Text changes in webshop view

### ISSUE THREAD

**Issue by owlRike** [lokalkauf/lokalkauf-frontend#245]
Change the text in the screenshot to following:
Gebe hier die Adresse Deines Online-Shops ein:

Dein Online-Shop

speichern

![grafik](https://user-images.githubusercontent.com/64211488/102052229-2a840680-3de6-11eb-92c8-c4f2cfa4cf85.png)

**Comment by Dipanjana1990** [comment]
The text ad the button are not as stated above in the requirement.

![image](https://user-images.githubusercontent.com/68644410/111676299-51efd280-881e-11eb-836c-5129992b5993.png)

**Comment by Dipanjana1990** [comment]
Needs to be changed to "Dein Online-Shop". Please change the  spelling of "Adresse" also

![image](https://user-images.githubusercontent.com/68644410/112200992-1c792980-8c10-11eb-8974-09e927f89f90.png)

**Comment by christianaschoff** [comment]
@Dipanjana1990 all buttons should start with a capital letter.
typo is corected

**Comment by Dipanjana1990** [comment]
The spelling of "Online-shop" is now corrected.
Speichern should ideally start with small s but is not that big a issue

![image](https://user-images.githubusercontent.com/68644410/118528162-5105ef00-b742-11eb-962b-b34e64ec1295.png)
