### ISSUE TITLE
Delete "Online Bezahlung" in shopify description

### ISSUE THREAD

**Issue by owlRike** [lokalkauf/lokalkauf-frontend#246]
![grafik](https://user-images.githubusercontent.com/64211488/102052556-8484cc00-3de6-11eb-98f0-c71c43f267b6.png)

**Comment by Dipanjana1990** [comment]
Tested and Passed.
![image](https://user-images.githubusercontent.com/68644410/111676976-04279a00-881f-11eb-8ac8-f4b08c136c20.png)
