### ISSUE TITLE
Add note between headline and table, that the shop information are from "Stand: 11.12.2020" (see ppt changes)

### ISSUE THREAD

**Issue by owlRike** [lokalkauf/lokalkauf-frontend#247]
![grafik](https://user-images.githubusercontent.com/64211488/102052740-d3326600-3de6-11eb-84ab-01b94eadb45e.png)

**Comment by Dipanjana1990** [comment]
tested and is Okay

![image](https://user-images.githubusercontent.com/68644410/112731592-94a95d00-8f38-11eb-828a-a2c0ae4ba102.png)
