### ISSUE TITLE
Entering the webshop or website URL doesn't work, when starting with a capital H, e.g. Https://meinshop.de

### ISSUE THREAD

**Issue by owlRike** [lokalkauf/lokalkauf-frontend#248]
![grafik](https://user-images.githubusercontent.com/64211488/102053310-d1b56d80-3de7-11eb-9b0d-3ba9296a3d1a.png)
![grafik](https://user-images.githubusercontent.com/64211488/102053329-daa63f00-3de7-11eb-9314-0e6dbbecd454.png)

**Comment by christianaschoff** [comment]
This is common behavior, but I look into it.
At least we should provide an error message

**Comment by Dipanjana1990** [comment]
In the Angebot page the url starting with capital H is not accepted and an error message is displayed but at the same time the same Url is accepted in the Online-Shop Page

![image](https://user-images.githubusercontent.com/68644410/112732353-bbb45e80-8f39-11eb-86f9-31c1690996b6.png)

![image](https://user-images.githubusercontent.com/68644410/112732359-c5d65d00-8f39-11eb-953f-4b0e6588b0d3.png)

@christianaschoff :Should we not expect similar behaviour in both the pages and if yes which behaviour is expected?

**Comment by christianaschoff** [comment]
i am sorry - i overlooked the 2nd dialog :/. will fix this soon - i promise

**Comment by Dipanjana1990** [comment]
The url starting with capital H is getting accepted in both "Angebot" and "Online-Shop".
@christianaschoff : Please check
![image](https://user-images.githubusercontent.com/68644410/117345796-3f515b80-aea7-11eb-9337-4cc413af8a6d.png)

![image](https://user-images.githubusercontent.com/68644410/117345866-585a0c80-aea7-11eb-9ae5-d4db33d19723.png)

**Comment by christianaschoff** [comment]
@Dipanjana1990 just checked on lokalkauf-staging and everything seems to work fine with both fields.
Maybe it is a caching-issue… i needed to reload the page without caching to see the changes.
After that everything worked fine after that.

Maybe I got it wrong, but captial h should be accepted as well.

**Comment by Dipanjana1990** [comment]
Now Both field are showing a message when url starts with capital H and both are still getting accepted. I guess this is what is expected.

![image](https://user-images.githubusercontent.com/68644410/117698465-104b2a80-b1c4-11eb-9ca2-442fa860136c.png)
![image](https://user-images.githubusercontent.com/68644410/117698548-235dfa80-b1c4-11eb-9a5f-a55a635485de.png)
![image](https://user-images.githubusercontent.com/68644410/117698613-3244ad00-b1c4-11eb-9715-55cfdf786694.png)
![image](https://user-images.githubusercontent.com/68644410/117698678-412b5f80-b1c4-11eb-9bfb-4c25e31ef3bd.png)
