### ISSUE TITLE
Delete onlineshop after save again

### ISSUE THREAD

**Issue by christianaschoff** [lokalkauf/lokalkauf-frontend#250]
Delete the shop-link after it was saved once does not work

**Comment by Dipanjana1990** [comment]
@christianaschoff : Did you mean deleting the profile?
![image](https://user-images.githubusercontent.com/68644410/112749462-97e92b00-8fc2-11eb-803f-23463f786c66.png)

**Comment by christianaschoff** [comment]
@Dipanjana1990 it was not possible to remove the online-shop link.
What do you mean by "output of the field"?
As long as there is no error message when saving everything is fine

**Comment by Dipanjana1990** [comment]
tested and is Okay

![image](https://user-images.githubusercontent.com/68644410/118530002-70058080-b744-11eb-918f-2c18c14d3ca4.png)
