### ISSUE TITLE
Button can be clicked, but looks disabled

### ISSUE THREAD

**Issue by darkblackside** [lokalkauf/lokalkauf-frontend#258]
https://lokalkauf-security-testing.web.app/trader-detail/ONwSC9cRcabwC7zUChhQodqhR8x1

The Button "Händler direkt kontaktieren" can be pressed, but it looks disabled. It should be truly disabled or enabled when usable.

**Comment by Dipanjana1990** [comment]
In staging the button "Händler direkt kontaktieren" is enabled 
![image](https://user-images.githubusercontent.com/68644410/115600031-856dc300-a2dc-11eb-91b5-6c45ee7de7af.png)
But in Firebaseapp link provided above it seems still not to function

**Comment by christianaschoff** [comment]
Ok, doesnt matter - staging is the single source of truth here. Forget about security testing.
