### ISSUE TITLE
Members&Founders

### ISSUE THREAD

**Issue by MaximilianSei** [lokalkauf/lokalkauf-frontend#273]
New lists or members

**Comment by MaximilianSei** [comment]
Alexander Schieweck - Gründer, aktives Mitglied
Björn Merschmeier - Gründer, aktives Mitglied
Christian Aschoff - Gründer, aktives Mitglied
Dipanjana Chaudhuri – aktives Mitglied
Esther Constantin – aktives Mitglied
Friederike Seidel – Vorstand, Gründer, aktives Mitglied
Kai Nitsch – Gründer
Konstantin Bücheler -Gründer, aktives Mitglied
Ilja Leyberman - Gründer, passives Mitglied
Lukas Schmyrczyk – Vorstand, Gründer, aktives Mitglied
Maximilian Seidel – Vorstand, Gründer, aktives Mitglied
Mina Paulus - Gründer, aktives Mitglied
Patrick Simmelbauer - Gründer, passives Mitglied
Philipp Salinski - Gründer, passives Mitglied
Stefan Klement - Gründer, passives Mitglied
Volkan Karakulak - Gründer, aktives Mitglied

Supporter
Christian Welkenbach - Datenschutz (TCI Rechtsanwälte)
Elena Funk - Presse
Mahesh Iyer - Konzeption Storyboard Film (Brandscape GmbH)
Skirmante Rudaviciute – UX/UI Design 
Stefan Scholz – Schnitt Film (Brandscape GmbH)

Vielen Dank für Eure Unterstützung des lokalen Einzelhandels und der Gastronomie!

**Comment by MaximilianSei** [comment]
[Uploading Text_lokalkauf_NEU.docx…]()

**Comment by MaximilianSei** [comment]
New Text in the document and everything "Mittig" :)

**Comment by christianaschoff** [comment]
@MaximilianSei I can not download the document. The link is not facing any document

**Comment by MaximilianSei** [comment]
Check Slack! :)Gesendet mit der mobilen Mail AppAm 21.05.21 um 18:04 schrieb Christian Aschoff
                
            
            
                
                    Von: "Christian Aschoff" ***@***.***>Datum: 21. Mai 2021An: "lokalkauf/lokalkauf-frontend" ***@***.***>Cc: "Mention" ***@***.***>,"MaximilianSei" ***@***.***>Betreff: Re: [lokalkauf/lokalkauf-frontend] Members&Founders (#273)
                
                
@MaximilianSei I can not download the document. The link is not facing any document

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/lokalkauf/lokalkauf-frontend/issues/273#issuecomment-846064094",
"url": "https://github.com/lokalkauf/lokalkauf-frontend/issues/273#issuecomment-846064094",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
