### ISSUE TITLE
jQuery vulnerability

### ISSUE THREAD

**Issue by mfranzke** [LokalKauf/lokalkauf-frontend#42]
'jQuery@3.3.1' has 1 known vulnerability (1 medium). See 'https://snyk.io/vuln/npm:jquery' for more information.

**Comment by aschieweck** [comment]
I think jQuery is only imported for Bootstrap, which I'm not quite sure if we actually need it. @thecodemonkey or @patsimm could you look into this and update or maybe even remove Bootstrap and its dependencies while you are working on the redesign?

**Comment by patsimm** [comment]
We got rid of jquery and bootstrap all together in the redesign branch. We should probably merge that asap as it already is a fully functional version right now.

**Comment by patsimm** [comment]
jQuery was removed with #37
