### ISSUE TITLE
Import german Postal-GeoData in Firebase

### ISSUE THREAD

**Issue by thecodemonkey** [lokalkauf/lokalkauf-frontend#49]
To avoid the limits and high costs of 3'rd party providers, we can provide our own geocoding service. For this we need geodata on postcode level.
These can be downloaded here for free.

https://public.opendatasoft.com/explore/dataset/postleitzahlen-deutschland/table/

The export must be imported into the Firebase afterwards. Furthermore, the already existing geo.service should be linked to the Firebase DB .

**Comment by lukaesch** [comment]
Test scenario:
1. Verify geo service manually on landing page with random city from each state in Germany: OK

**Comment by christianaschoff** [comment]
done
