### ISSUE TITLE
The Trader should visually confirm the location of his shop.

### ISSUE THREAD

**Issue by thecodemonkey** [lokalkauf/lokalkauf-frontend#54]
**problem.**

The locations of the dealers are currently calculated in the background. If the address is not correct, then the wrong locations can be determined and the dealer will not be found in the desired region.

**solution:**

To avoid this, the dealer should visually confirm his address when registering or changing his address. A map will be displayed as a dialog or something like that. The pin is automatically determined based on his address, or he can move the pin, etc. 
The location or address is taken from the pin and is given and saved directly when saving. This ensures that each location has been directly validated by the dealer himself.

**Comment by patsimm** [comment]
@thecodemonkey Isn't this done already?

**Comment by christianaschoff** [comment]
done
