### ISSUE TITLE
Testimonials: should be like the regular image slider, but should not rotate automatically. Navigation-Link to trader shop

### ISSUE THREAD

**Issue by christianaschoff** [lokalkauf/lokalkauf-frontend#74]

**Comment by patsimm** [comment]
should not rotate automatically?

**Comment by christianaschoff** [comment]
Yeah, the user should be able to flip the testimonials on her own by arrows. Should be reconsidered maybe?

**Comment by patsimm** [comment]
Maybe both should be possible? So event if the user doesn't flip throug he/she will be able to see all the testimonials?
