### ISSUE TITLE
Trader-Registration is visible on Trader-List that has no trader results, even if loggend in

### ISSUE THREAD

**Issue by christianaschoff** [lokalkauf/lokalkauf-frontend#78]
The text of the button should be correct or the button should not be visible at all

**Comment by thecodemonkey** [comment]
**Test scenario 1:**

1. GIVEN:                  user ist not logged in.
2. ACT:                      try to find some traders in the desert
3. EXPECTATION:    in trader overview, you should see the registration button.

**Test scenario 2:** 

1. GIVEN:                   trader ist logged in
2. ACT:                       try to find some traders in the desert
3. EXPECTATION:     in trader overview, you should not see the registration button!
