### ISSUE TITLE
improvement of the postcode search

### ISSUE THREAD

**Issue by thecodemonkey** [lokalkauf/lokalkauf-frontend#84]
If you search for the city, only the cities and not the postcode areas should be offered for selection.

Default radius should be at least 20 km.

**Comment by owlRike** [comment]
When I type in a city the city is shown first, but the postcode options follow. I think that's fine, in case I will refine my search. 
If that's how it should look like test was succesful :-)

**Comment by thecodemonkey** [comment]
yes, it‘s Not a bug it’s a Feature 😉
