### ISSUE TITLE
Some Carousel images are turned and stretched

### ISSUE THREAD

**Issue by owlRike** [lokalkauf/lokalkauf-frontend#97]
![IMG_3585](https://user-images.githubusercontent.com/64211488/80527105-2361d280-8994-11ea-8755-69c6f073daf9.PNG)
![IMG_3586](https://user-images.githubusercontent.com/64211488/80527115-278df000-8994-11ea-821e-87097f8aa410.PNG)

When opening a picture in a lightbox the picture is turned around and stretched – see attached screenshots

**Comment by christianaschoff** [comment]
can you provide the specific image please?

**Comment by owlRike** [comment]
> 
> 
> @owlRike can you provide the specific image please?

It wasn't my profile, so I cannot provide the image. The profile is called Testfirma Brühl, located in Testweg 23 Wiesbaden.

**Comment by christianaschoff** [comment]
Guess with the new carousel this will work fine. Tested it with my local implementation.

![grafik](https://user-images.githubusercontent.com/13931688/82741130-63c42e80-9d4f-11ea-8ebd-08a59c985c74.png)
![grafik](https://user-images.githubusercontent.com/13931688/82741140-6e7ec380-9d4f-11ea-9a4a-2f4b0ca534fb.png)
